version: '2.1'

jobs:
    phpcs:
        docker:
            - image: steevanb/php-code-sniffs:4.0.1
        working_directory: /app
        steps:
            - checkout
            - run:
                name: phpcs
                command: /var/php-code-sniffs/bin/phpcs

workflows:
    version: '2.1'
    CI:
        jobs:
            - phpcs
