name: CI
on: [push]

jobs:
    phpcs:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2
            -
                name: bin/composer update
                run: bin/composer update
            -
                name: bin/phpcs
                run: bin/phpcs
